export const ProductTypes = {
  PRODUCT_INIT: "PRODUCT_INIT",
  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAILURE: "PRODUCT_FAILURE",
  DETAIL_PRODUCT_REQUEST: "DETAIL_PRODUCT_REQUEST",
  DETAIL_PRODUCT_SUCCESS: "DETAIL_PRODUCT_SUCCESS",
  DETAIL_PRODUCT_FAILURE: "DETAIL_PRODUCT_FAILURE",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}